package databasestorage

import (
	"context"
	"database/sql"
	"time"

	"github.com/WeisseNacht18/url-shortener/internal/logger"
	_ "github.com/jackc/pgx/v5/stdlib"
)

type DatabaseStorage struct {
	database *sql.DB
}

func NewDatabaseStorage(dsn string) *DatabaseStorage {
	database, err := sql.Open("pgx", dsn)
	if err != nil {
		logger.Logger.Fatalln(err)
	}

	const query = `CREATE TABLE IF NOT EXISTS public.url
			(
				id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
				short_url character varying COLLATE pg_catalog."default",
				original_url character varying COLLATE pg_catalog."default",
				CONSTRAINT url_pk PRIMARY KEY (id)
			)`

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	_, err = database.ExecContext(ctx, query)
	if err != nil {
		logger.Logger.Fatalln(err)
	}

	storage := DatabaseStorage{
		database: database,
	}

	return &storage
}

func (storage *DatabaseStorage) AddURL(originalURL string, shortURL string) (ok bool) {
	err := storage.SaveURLToDatabase(shortURL, originalURL)
	if err == nil {
		ok = true
	} else {
		ok = false
	}
	return
}

func (storage *DatabaseStorage) GetURL(shortURL string) (originalURL string, ok bool) {
	originalURL, ok = storage.GetURLFromDatabase(shortURL)
	return
}

func (storage *DatabaseStorage) CheckStorage() error {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	err := storage.database.PingContext(ctx)
	logger.Logger.Infoln(err)

	return err
}

func (storage *DatabaseStorage) CheckURL(originalURL string) (shortLink string, hasURL bool) {
	hasURL = false

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	row := storage.database.QueryRowContext(ctx, "SELECT short_url FROM url WHERE original_url = $1 LIMIT 1", originalURL)

	err := row.Scan(&shortLink)

	if err != nil {
		logger.Logger.Infoln(err)
		return
	}

	hasURL = true

	return
}

func (storage *DatabaseStorage) Close() {
	storage.database.Close()
}

func (storage *DatabaseStorage) SaveURLToDatabase(shortURL string, originalURL string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	_, err := storage.database.ExecContext(ctx, "INSERT INTO url (short_url, original_url) VALUES ($1, $2)", shortURL, originalURL)

	return err
}

func (storage *DatabaseStorage) GetURLFromDatabase(shortURL string) (result string, ok bool) {
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	var originalURL string

	row := storage.database.QueryRowContext(ctx, "SELECT original_url FROM url WHERE short_url = $1 LIMIT 1", shortURL)

	err := row.Scan(&originalURL)
	if err != nil {
		return originalURL, false
	}

	return originalURL, true
}
